# Generated by Django 5.2 on 2025-05-02 02:14

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_familia', models.CharField(max_length=100, verbose_name='Nome da Família')),
                ('nome_responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('cpf_responsavel', models.CharField(max_length=14, unique=True, verbose_name='CPF Responsável')),
                ('tipo_recebimento', models.CharField(choices=[('estipulado', 'Estipulado'), ('nao_estipulado', 'Não Estipulado')], default='estipulado', max_length=20, verbose_name='Tipo Recebimento')),
                ('renda_familia', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Renda da Família')),
                ('quantidade_integrantes', models.PositiveIntegerField(verbose_name='Qtd. Membros')),
                ('tipo_moradia', models.CharField(max_length=50, verbose_name='Moradia')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado')], default='ativo', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
                'db_table': 'familia',
            },
        ),
        migrations.CreateModel(
            name='LocalEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(max_length=50, verbose_name='Nome do Local')),
                ('funcionarios', models.CharField(max_length=150, verbose_name='Funcionários')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('coordenador', models.CharField(max_length=80, verbose_name='Coordenador')),
            ],
            options={
                'verbose_name': 'Local de Entrega',
                'verbose_name_plural': 'Locais de Entrega',
                'db_table': 'local',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_usuario', models.CharField(max_length=80, verbose_name='Nome')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='E-mail')),
                ('tipo_usuario', models.CharField(choices=[('MASTER', 'Master'), ('COORDENADOR', 'Coordenador'), ('OPERACAO', 'Operacional')], default='OPERACAO', max_length=20, verbose_name='Tipo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
