# Generated by Django 5.2 on 2025-05-31 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='cpf_responsavel',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='nome_responsavel',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='telefone',
        ),
        migrations.AddField(
            model_name='localentrega',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='id',
            field=models.AutoField(db_column='id_familia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(db_column='id_usuario', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PessoaAutorizada',
            fields=[
                ('id_pessoa_autorizada', models.AutoField(db_column='id_pessoa_autorizada', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_autorizadas', to='core.familia')),
            ],
            options={
                'db_table': 'pessoa_autorizada',
                'unique_together': {('cpf', 'familia')},
            },
        ),
    ]
